### ISSUE TITLE
Планы на будущее

### ISSUE THREAD

**Issue by sarseniy** [DGAP-clicker-2020/clicker#2]
**TODO**

- [x] Задокументировать код

- [x] Добавить отображение статистики

- [x] Добавить деньги

- [x] Добавить магазин улучшений

- [x] Реализовать начисление денег при закрытой игре

- [x] Добавить графики (фон, мишень, эффекты)

- [x] Сделать приятный README

- [x] Подключить БД

**Comment by sarseniy** [comment]
> Добавить отображение статистики

> Добавить графики (фон, мишень, эффекты)

Частично сделано
